config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get :dashboard, to: 'home#dashboard'
  get :coming_soon, to: 'home#coming_soon'

  resources :users, path: 'accounts' do
    resources :responses
  end

  resources :projects do
    resources :project_memberships do
      get :users_list, on: :collection
    end
  end
  root 'home#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, presence: true

  has_many :project_memberships
  has_many :users, through: :project_memberships

  belongs_to :location

  accepts_nested_attributes_for :project_memberships, allow_destroy: true
  accepts_nested_attributes_for :users, allow_destroy: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    respond_to do | format |
      if @project.save
        flash["success"] = "Project created successfully"
        redirect_to
      else
        flash["error"] = "Unable to create Project at this moment"
        render action: :new
      end
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    respond_to do | format |
      if @project.update_attributes(project_params)
        flash["success"] = "Project updated successfully"
        redirect_to ##
      else
        flash["error"] = "Unable to update Project at this moment"
        render action: :edit
      end
    end
  end

private
  def project_params
    params.require(:project).permit()
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<p>Find me in app/views/projects/edit.html.erb</p>

app/views/projects/index.html.erb
<h1>Listing Projects</h1>

<table data-toggle="table" class="table table-striped">
  <thead>
    <tr>
      <th data-field="s_id">S.No</th>
      <th data-field="name">Name</th>
      <th data-field="location">Location</th>
      <th data-field="size">Team Size</th>
      <th data-field="actions">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% s_no = 1 %>
    <% @projects.each do | project | %>
      <tr class="<%= cycle("table-striped", "") -%>">
        <td data-field="s_id"><%= s_no %></td>
        <td data-field="s_id"><%= project.name %></td>
        <td data-field="s_id"><%= project.location.name %></td>
        <td data-field="s_id"><%= project.team_size %></td>
        <td data-field="s_id"><%= link_to "<i class='fa fa-camera-retro' aria-hidden='true'></i>".html_safe, project_path(project) %> | <%= link_to "Create Membership", new_project_project_membership_path(project) %></td>
      </tr>
      <% s_no += 1 %>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<h1>Projects#new</h1>
<p>Find me in app/views/projects/new.html.erb</p>

app/views/projects/show.html.erb
<h1>Projects#show</h1>
<p>Find me in app/views/projects/show.html.erb</p>