config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get :dashboard, to: 'home#dashboard'
  get :coming_soon, to: 'home#coming_soon'

  resources :users, path: 'accounts' do
    resources :responses
  end

  resources :projects do
    resources :project_memberships do
      get :users_list, on: :collection
    end
  end
  root 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "BugTrackingTool" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">BugTrackingTool</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "<i class='fa fa-info'></i>&nbsp; Our Team".html_safe, "/path1"  %></li>
            <li><%= link_to "Setting-Up", coming_soon_path  %></li>
            <li>
              <% if user_signed_in? %>
                <%= link_to "<i class='fa fa-sign-out'></i>&nbsp; Logout".html_safe, destroy_user_session_path, method: :delete %>
              <% else %>
                <%= link_to "<i class='fa fa-sign-in'></i>&nbsp; Sign-in".html_safe, new_user_session_path %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row row-offcanvas row-offcanvas-left">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <!-- sidebar -->
        <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
          <div class="list-group">
            <%= link_to "<i class='fa fa-tachometer'></i>&nbsp; My Dashboard".html_safe, current_user ? dashboard_path : "javascript:void(0);", class: "list-group-item" %>
            <%= link_to "<i class='fa fa-pencil fa-fw'></i>&nbsp; Report a Bug".html_safe, current_user ? new_user_response_path( current_user ) : "javascript:void(0);", class: "list-group-item" %>
            <%= link_to "<i class='fa fa-folder'></i>&nbsp; Submitted Bugs".html_safe, current_user ? user_responses_path( current_user, req_type: "completed" ) : "javascript:void(0);", class: "list-group-item" %>
            <%= link_to "<i class='fa fa-tasks'></i>&nbsp; Approved Bugs".html_safe, current_user ? user_responses_path( current_user, req_type: "approved" ) : "javascript:void(0);", class: "list-group-item" %>
            <%= link_to "<i class='fa fa-cog fa-fw'></i>&nbsp; Manage Projects".html_safe, projects_path, class: "list-group-item" %>
            <%= link_to "<i class='fa fa-user'></i>&nbsp; My Profile".html_safe, "javascript:void(0);", class: "list-group-item" %>
            <%= link_to "<i class='fa fa-bar-chart'></i>&nbsp; Charts / Reports".html_safe, coming_soon_path, class: "list-group-item" %>
          </div>
        </div>
      </div>

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->
    <%= yield :page_javascript %>
  </body>
</html>

app/views/layouts/coming_soon.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "BugTrackingTool: Coming Soon" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <style>
      /* ==== Google font ==== */
      @import url('http://fonts.googleapis.com/css?family=Lato:400,300,700,900');
      body { background: #6ac0bd; font-family: 'Lato', sans-serif; font-weight: 300; font-size: 16px; color: #555; line-height: 1.6em; -webkit-font-smoothing: antialiased; -webkit-overflow-scrolling: touch; }

      h1, h2, h3, h4, h5, h6 { font-family: 'Lato', sans-serif; font-weight: 300; color: #444; }
      h1 { font-size: 40px; }
      h3 { font-weight: 400; }
      h4 { font-weight: 400; font-size: 20px; }
      p { margin-bottom: 20px; font-size: 16px; }
      a { color: #ACBAC1; word-wrap: break-word; 
        -webkit-transition: color 0.1s ease-in, background 0.1s ease-in;
        -moz-transition: color 0.1s ease-in, background 0.1s ease-in;
        -ms-transition: color 0.1s ease-in, background 0.1s ease-in;
        -o-transition: color 0.1s ease-in, background 0.1s ease-in;
        transition: color 0.1s ease-in, background 0.1s ease-in;
      }
      a:hover, a:focus { color: #4F92AF; text-decoration: none; outline: 0; }
      a:before, a:after {
        -webkit-transition: color 0.1s ease-in, background 0.1s ease-in;
        -moz-transition: color 0.1s ease-in, background 0.1s ease-in;
        -ms-transition: color 0.1s ease-in, background 0.1s ease-in;
        -o-transition: color 0.1s ease-in, background 0.1s ease-in;
        transition: color 0.1s ease-in, background 0.1s ease-in;
      }

      .alignleft { text-align: left; }
      .alignright { text-align: right; }
      .aligncenter { text-align: center; }
      .btn { display: inline-block; padding: 10px 20px; margin-bottom: 0; font-size: 14px; font-weight: normal; line-height: 1.428571429; text-align: center; white-space: nowrap; vertical-align: middle; cursor: pointer;
        -webkit-user-select: none; -moz-user-select: none; -ms-user-select: none; -o-user-select: none; user-select: none; background-image: none; border: 1px solid transparent; border-radius: 0; 
      }
      .btn-theme { color: #fff; background-color: #4F92AF; border-color: #4F92AF; }
      .btn-theme:hover  { color: #fff; background-color: #444; border-color: #444; }
      form.signup input[type=email] { height: 42px; width: 200px; border-radius: 0; border: none; }
      form.signup button.btn { font-weight: 700; }
      form.signup input.form-control:focus { border-color: #fd680e; }

      /* wrapper */
      #wrapper { text-align: center; background: url(../images/main-bg-compressor.jpg) no-repeat center top;
        background-attachment: relative; background-position: center center; box-sizing:border; width: 100%;
        -webkit-background-size: 100%; -moz-background-size: 100%; -o-background-size: 100%; background-size: 100%;
        -webkit-background-size: cover; -moz-background-size: cover; -o-background-size: cover; background-size: cover;
      }

      #wrapper > .container { padding-top: 50px; }
      #wrapper h1 { margin-top: 60px; margin-bottom: 40px; color: #fff; font-size: 45px; font-weight: 900; letter-spacing: -1px; }
      h2.subtitle { color: #fff; font-size: 24px; }

      /* countdown */
      #countdown { font-size: 48px; color: #fff; line-height: 1.1em; margin: 40px 0 60px; }
      /* footer */
      p.copyright { margin-top: 50px; color: #fff; text-align: center; }
      .cloud { position: fixed; bottom:40px; left:20px; }
      .cloud.fliped img {
        -moz-transform: scaleX(-1);
        -o-transform: scaleX(-1);
        -webkit-transform: scaleX(-1);
        transform: scaleX(-1);
        filter: FlipH;
        -ms-filter: "FlipH";
      }
      .cloud.pos1 { right:20px; left:auto; bottom: 70px; }
      .cloud.pos1 img { width:100px; }
      .cloud.pos2 { bottom: 150px; right:50px; left:auto; }
      .cloud.pos2 img { width:150px; }
      .cloud.pos3 { bottom: 200px; left:120px; }
      .cloud.pos3 img { width:180px; }
      .result { position: absolute; top:0px; padding: 7px 10px 7px 20px; left:auto; right:0px; color: #fff; }
      .result.success { background: #2ecc71; }
      .result.error { background: #2c3e50; }
      .result span { margin-left: 10px; }
      .result.error span { margin-right: 5px; }

      @media only screen 
      and (min-device-width : 320px) 
      and (max-device-width : 480px) { 
        .cloud { display: none; }
        input[type=email] { width:100% !important; }
      }
    </style>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="cloud floating">
      <%= image_tag "cloud.png", alt: "BTT" %>
    </div>

    <div class="cloud pos1 fliped floating">
      <%= image_tag "cloud.png", alt: "BTT" %>
    </div>

    <div class="cloud pos2 floating">
      <%= image_tag "cloud.png", alt: "BTT" %>
    </div>

    <div class="cloud pos3 fliped floating">
      <%= image_tag "cloud.png", alt: "BTT" %>
    </div>

    <div id="wrapper">
      <div class="container">
        <%= yield %>
        <div class="row">
          <div class="col-lg-6 col-lg-offset-3">
            <p class="copyright">Copyright &copy; 2014 - <a href="http://scoopthemes.com">ScoopThemes.com</a></p>
          </div>
        </div>
      </div>
    </div>
    <script>
      $(document).ready( function () {
        $('#wrapper').height($(document).height());
        // I only have one form on the page but you can be more specific if need be.
        var $form = $('form');
        if ( $form.length > 0 ) {
          $('form input[type="submit"]').bind('click', function ( event ) {
            if ( event ) event.preventDefault();
            // validate_input() is a validation function I wrote, you'll have to substitute this with your own.
            if ( $form.validate() ) { register($form); }
          });
        }
      });

      function appendResult(userText , className, iconClass){
        var resultHTML = "<div class='stretchLeft result "+ className + "'>" + userText + " <span class='fa fa-" + iconClass + "'></span>" + "</div>";
        $('body').append(resultHTML);
        $('.result').delay(10000).fadeOut('1000');
      }

      function register($form) {
        $.ajax({
          type: $form.attr('method'),
          url: $form.attr('action'),
          data: $form.serialize(),
          cache       : false,
          dataType    : 'json',
          contentType: "application/json; charset=utf-8",
          error       : function(err) { alert("Could not connect to the registration server. Please try again later."); },
          success     : function(data) {
            if (data.result !== "success") {
              appendResult('Wrong Email Or You Are Already Registered, Try Again', 'error', 'exclamation');
            } else {
              // It worked, carry on...
              appendResult('Successful, Check Your Email For Confirmation ', 'success', 'check');
            }
          }
        });
      }
    </script>
  </body>
</html>